name: Main

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-workflows:
    name: Check workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        id: download-actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/7fdc9630cc360ea1a469eed64ac6d78caeda1234/scripts/download-actionlint.bash) 1.6.22
        shell: bash
      - name: Check workflow files
        run: ${{ steps.download-actionlint.outputs.executable }} .github/workflows/build.yml .github/workflows/case.yml .github/workflows/crowdin.yml .github/workflows/dependency_review.yml .github/workflows/lint.yml .github/workflows/main.yml .github/workflows/nightly.yml .github/workflows/security-code-scanner.yml .github/workflows/trivy.yml -color
        shell: bash

  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets:
      SEGMENT_ANALYTICS_KEY: ${{ secrets.SEGMENT_ANALYTICS_DEV_KEY }}
      LD_CLIENT_ID: ${{ secrets.LD_CLIENT_ID }}
      SENTRY_KEY: ${{ secrets.SENTRY_KEY }}

  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    secrets:
      SEGMENT_ANALYTICS_KEY: ${{ secrets.SEGMENT_ANALYTICS_DEV_KEY }}
      LD_CLIENT_ID: ${{ secrets.LD_CLIENT_ID }}
      SENTRY_KEY: ${{ secrets.SENTRY_KEY }}

  case:
    name: Case
    uses: ./.github/workflows/case.yml
    secrets:
      SEGMENT_ANALYTICS_KEY: ${{ secrets.SEGMENT_ANALYTICS_DEV_KEY }}
      LD_CLIENT_ID: ${{ secrets.LD_CLIENT_ID }}
      SENTRY_KEY: ${{ secrets.SENTRY_KEY }}

  all-jobs-completed:
    name: All jobs completed
    runs-on: ubuntu-latest
    needs:
      - check-workflows
      - build
      - lint
      - case
    outputs:
      PASSED: ${{ steps.set-output.outputs.PASSED }}
    steps:
      - name: Set PASSED output
        id: set-output
        run: echo "PASSED=true" >> "$GITHUB_OUTPUT"

  all-jobs-pass:
    name: All jobs pass
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: all-jobs-completed
    steps:
      - name: Check that all jobs have passed
        run: |
          passed="${{ needs.all-jobs-completed.outputs.PASSED }}"
          if [[ $passed != "true" ]]; then
            exit 1
          fi
